Web/TMXN.Web/Controllers/AwardsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TMXN.Data.Common.InputModels.Awards;
using TMXN.Services.Data;
using TMXN.Web.ViewModels.Awards;

namespace TMXN.Web.Controllers
{
    public class AwardsController : BaseController
    {
        private readonly IAwardsService awardsService;

        public AwardsController(IAwardsService awardsService)
        {
            this.awardsService = awardsService;
        }
        public async Task<IActionResult> All()
        {
            var viewModel = new AwardListViewModel
            {
                Awards = await this.awardsService.GetAll<AwardViewModel>(),
            };
            return this.View(viewModel);
        }
     
    }
}

Web/TMXN.Web/Controllers/BracketsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TMXN.Services.Data;
using TMXN.Web.ViewModels.Brackets;
using TMXN.Web.ViewModels.Teams;
using TMXN.Web.ViewModels.Tournaments;

namespace TMXN.Web.Controllers
{
    public class BracketsController : BaseController
    {
        private readonly IBracketsService bracketsService;
        

        public BracketsController(IBracketsService bracketsService)
        {
            this.bracketsService = bracketsService;
            
        }

        public IActionResult All()
        {
            var viewModel = new BracketListViewModel
            {
                Brackets = this.bracketsService.GetAll<BracketViewModel>(),
            };
            return this.View(viewModel);
        }
       

    }
}

Web/TMXN.Web/Controllers/TeamsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TMXN.Data.Common.InputModels.Teams;
using TMXN.Data.Common.Repositories;
using TMXN.Data.Models;
using TMXN.Services.Data;
using TMXN.Web.ViewModels.Awards;
using TMXN.Web.ViewModels.Teams;

namespace TMXN.Web.Controllers
{
    [Authorize]
    public class TeamsController : BaseController
    {
        private readonly ITeamsService teamsService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IDeletableEntityRepository<Team> teamsRepository;
        private readonly IUsersService usersService;
        private readonly IAwardsService awardsService;

        public TeamsController(ITeamsService teamsService,UserManager<ApplicationUser> userManager,IDeletableEntityRepository<Team> teamsRepository,IUsersService usersService,IAwardsService awardsService)
        {
            this.teamsService = teamsService;
            this.userManager = userManager;
            this.teamsRepository = teamsRepository;
            this.usersService = usersService;
            this.awardsService = awardsService;
        }
      
        public  IActionResult ShowAll(string criteria = null)
        {
            var viewModel = new TeamsListViewModel();
            var all = this.teamsService.GetAll<TeamViewModel>(criteria);
            viewModel.Teams = all;
            return this.View(viewModel);
        }
     
       

       
        public async Task<IActionResult> Leave(string id)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            await this.usersService.LeaveAsync(id, user);

            return this.RedirectToAction(nameof(this.ShowAll));

        }
        
        public async Task<IActionResult> Join(string id)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            await this.usersService.JoinAsync(id, user);


            return this.RedirectToAction(nameof(this.ShowAll));
        }

        
        public IActionResult TeamInfo(string id)
        {
            var viewModel = this.teamsService.GetInfo<TeamInfoViewModel>(id);
            
            return this.View(viewModel);
        }

       

        public IActionResult Ranklist()
        {
            var viewModel = new ListRanklistTeamViewModel
            {
                Teams = this.teamsService.GetRanklist<RanklistTeamViewModel>().ToList(),
            };
            return this.View(viewModel);
        }

       

       

    }
}

Web/TMXN.Web/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TMXN.Data.Models;
using TMXN.Services.Data;
using TMXN.Web.ViewModels.Users;

namespace TMXN.Web.Controllers
{
    [Authorize]
    public class UsersController : BaseController
    {
        private readonly IUsersService usersService;
        private readonly UserManager<ApplicationUser> userManager;

        public UsersController(IUsersService usersService,UserManager<ApplicationUser> userManager)
        {
            this.usersService = usersService;
            this.userManager = userManager;
        }
        public async Task<IActionResult> All()
        {
            var currentUser = await this.userManager.GetUserAsync(this.User);
            var viewModel = new UserListViewModel
            {
                Users = await this.usersService.GetAll<UserFriendViewModel>(),
            };

            return this.View(viewModel);

        }

        public async Task<IActionResult> Add(string id)
        {
            var myUser = await this.userManager.GetUserAsync(this.User);

           await this.usersService.AddFriendToFriendlistAsync(id, myUser);

            return this.RedirectToAction(nameof(AddToFriendlistSuccessful));
        }

        public IActionResult AddToFriendlistSuccessful()
        {
            return this.View();
        }

        public IActionResult RemoveFromFriendlistSuccessful()
        {
            return this.View();
        }

        public async Task<IActionResult> Remove(string id)
        {
            var myUser = await this.userManager.GetUserAsync(this.User);

            await this.usersService.RemoveFriendFromFriendlistAsync(id, myUser);

            return this.RedirectToAction(nameof(RemoveFromFriendlistSuccessful));
        }

        public async Task<IActionResult> AllFriends()
        {
            var currentUser = await this.userManager.GetUserAsync(this.User);

            
            var viewModel = new FriendlistListViewModel
            {
                Friendlists = await this.usersService.AllFriendsAsync<UserFriendViewModel>(currentUser.Id),
            };


            return this.View(viewModel);
        }
    }
}

Web/TMXN.Web/Views/Shared/_DisplayTeamsPartial.cshtml
@model TMXN.Web.ViewModels.Teams.TeamViewModel
@using Microsoft.AspNetCore.Identity
@using TMXN.Data.Models
@inject UserManager<ApplicationUser> userManager


@{string userId = userManager.GetUserId(this.User);}


<div class="card mr-3" style="width: 15rem;">
    <img class="card-img-top" src="@Model.Logo" alt="Card image cap">
    <div class="card-body">
        <h5 class="card-title">@Model.Name</h5>
        <h2 class="card-title">@Model.Tag</h2>



        @if (Model.ApplicationUsers.Any(x => x.Id == userId))
        {
            <a href="/Teams/Leave?teamId=@Model.Id" type="button" class="btn btn-primary center-block">Leave!</a>
        }
        else
        {
            <a href="/Teams/Join?teamId=@Model.Id" type="button" class="btn btn-primary center-block">Join us!</a>
        }
        <a href="/Teams/TeamInfo?teamId=@Model.Id" type="button" class="btn btn-primary center-block">Info!</a>



    </div>
</div>

Web/TMXN.Web/Views/Shared/_Layout.cshtml
@using TMXN.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>

    <environment names="Development">
        <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" asp-append-version="true" />

        

        <link href="~/css/site.css" rel="stylesheet" asp-append-version="true" />

    </environment>
    <environment names="Staging,Production">
       
        <link href="~/css/site.min.css" rel="stylesheet" asp-append-version="true" />
    </environment>
</head>
<body>
    <header>
        <nav  class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        Awards
                        <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                        <li><a asp-controller="Teams" asp-action="Ranklist">Ranklist</a></li>
                        <li><a asp-controller="Awards" asp-action="All">See our awards</a></li>
                        <li><a asp-controller="Brackets" asp-action="All">Brackets</a></li>
                        <li role="separator" class="divider"></li>

                    </ul>
                </div>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Chat">Chat</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teams" asp-action="ShowAll">Teams</a>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="All">Players</a>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tournaments" asp-action="GetAll">Tournaments</a>
                        </li>
                        @*<li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Settings" asp-action="Index">Settings</a>
        </li>*@

                        @*<li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </li>*@



                    </ul>

                </div>

            </div>
        </nav>
    </header>
    
    <div class="container">
       
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>
        

    </div>
    
    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="p-1 mb-5 bg-info text-white text-center">TMXN Design - All Rights reserved</div>
        </div>
        
    </footer>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>


        @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>*@


        <script src="~/lib/signalr/dist/browser/signalr.min.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js" asp-append-version="true"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>

        <script src="~/lib/signalr/dist/browser/signalr.min.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
        <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js" asp-append-version="true"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        
    </environment>

    @this.RenderSection("Scripts", required: false)
</body>
</html>