Web/TMXN.Web/Controllers/HomeController.cs
namespace TMXN.Web.Controllers
{
    using System.Diagnostics;

    using TMXN.Web.ViewModels;

    using Microsoft.AspNetCore.Mvc;
    using TMXN.Services.Data;
    using TMXN.Web.ViewModels.News;
    using Microsoft.AspNetCore.Authorization;
    using TMXN.Services.Data.Contracts;
    using TMXN.Web.ViewModels.Chat;
    using System.Threading.Tasks;

    public class HomeController : BaseController
    {
        private readonly INewsFeedsService newsFeedsService;
        private readonly IChatRoomService chatRoomService;

        public HomeController(INewsFeedsService newsFeedsService,IChatRoomService chatRoomService)
        {
            this.newsFeedsService = newsFeedsService;
            this.chatRoomService = chatRoomService;
        }

        
        public IActionResult Index([FromQuery]string criteria = null)
        {
            var viewModel = new NewsFeedsListViewModel();
            var all = this.newsFeedsService.GetAll<NewsViewModel>(criteria);
            viewModel.News = all;

            

            return this.View(viewModel);
        }

        [Authorize]
        public async Task<IActionResult> Chat()
        {
            ChatViewModel viewModel = await this.chatRoomService.GetAllMessages();
            return this.View(viewModel);
        }
        public IActionResult Privacy()
        {
            return this.View();
        }

        public IActionResult HttpError(int statusCode)
        {
            if(statusCode == 404)
            {
                return this.View(statusCode);
            }
            return this.View("Error");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(
                new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }
    }
}

Web/TMXN.Web/Controllers/NewsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TMXN.Data.Common.InputModels.News;
using TMXN.Services.Data;
using TMXN.Services.Data.Contracts;
using TMXN.Web.ViewModels.News;

namespace TMXN.Web.Controllers
{
    public class NewsController : BaseController
    {
        private readonly INewsFeedsService newsService;
        

        public NewsController(INewsFeedsService newsService)
        {
            this.newsService = newsService;
           
        }
        public async Task<IActionResult> Info(string id)
        {
            var viewModel = await this.newsService.GetNewsById<NewsViewModel>(id);
            return this.View(viewModel);
        }

       

       
       


      


    }
}

Web/TMXN.Web/Controllers/TeamsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TMXN.Data.Common.InputModels.Teams;
using TMXN.Data.Common.Repositories;
using TMXN.Data.Models;
using TMXN.Services.Data;
using TMXN.Web.ViewModels.Awards;
using TMXN.Web.ViewModels.Teams;

namespace TMXN.Web.Controllers
{
    [Authorize]
    public class TeamsController : BaseController
    {
        private readonly ITeamsService teamsService;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IDeletableEntityRepository<Team> teamsRepository;
        private readonly IUsersService usersService;
        private readonly IAwardsService awardsService;

        public TeamsController(ITeamsService teamsService,UserManager<ApplicationUser> userManager,IDeletableEntityRepository<Team> teamsRepository,IUsersService usersService,IAwardsService awardsService)
        {
            this.teamsService = teamsService;
            this.userManager = userManager;
            this.teamsRepository = teamsRepository;
            this.usersService = usersService;
            this.awardsService = awardsService;
        }
      
        public  IActionResult ShowAll(string criteria = null)
        {
            var viewModel = new TeamsListViewModel();
            var all = this.teamsService.GetAll<TeamViewModel>(criteria);
            viewModel.Teams = all;
            return this.View(viewModel);
        }
     
       

       
        public async Task<IActionResult> Leave(string id)
        {
            var user = await this.userManager.GetUserAsync(this.User);
            await this.usersService.LeaveAsync(id, user);

            return this.RedirectToAction(nameof(this.ShowAll));

        }
        
        public async Task<IActionResult> Join(string id)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            await this.usersService.JoinAsync(id, user);


            return this.RedirectToAction(nameof(this.ShowAll));
        }

        
        public IActionResult TeamInfo(string id)
        {
            var viewModel = this.teamsService.GetInfo<TeamInfoViewModel>(id);
            
            return this.View(viewModel);
        }

       

        public IActionResult Ranklist()
        {
            var viewModel = new ListRanklistTeamViewModel
            {
                Teams = this.teamsService.GetRanklist<RanklistTeamViewModel>().ToList(),
            };
            return this.View(viewModel);
        }

       

       

    }
}

Web/TMXN.Web/Controllers/TournamentsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TMXN.Data.Common.InputModels.Tournaments;
using TMXN.Data.Models;
using TMXN.Services.Data;
using TMXN.Web.ViewModels.Tournaments;
using TMXN.Web.ViewModels.Tournaments;

namespace TMXN.Web.Controllers
{
    [Authorize]
    public class TournamentsController : BaseController
    {
        private readonly ITournamentsService tournamentsService;
        private readonly UserManager<ApplicationUser> userManager;

        public TournamentsController(ITournamentsService tournamentsService,UserManager<ApplicationUser> userManager)
        {
            this.tournamentsService = tournamentsService;
            this.userManager = userManager;
        }
       
        public IActionResult GetAll(string gametype = null)
        {
            var viewModel = new TournamentsListViewModel
            {
                Tournaments = this.tournamentsService.All<TournamentsViewModel>(gametype),
            };

            return this.View(viewModel);
        }

       

        
        public async Task<IActionResult> Participate(int id)
        {
            var user = await this.userManager.GetUserAsync(this.User);


            await this.tournamentsService.ParticipateAsync(user.Id, id);

            return this.Redirect("/Tournaments/Success");
        }

        public async Task<IActionResult> Out(int id)
        {
            var user = await this.userManager.GetUserAsync(this.User);

            int tournamentId = await this.tournamentsService.RemoveTeamFromTournamentAsync(id, user.Id);

            if(tournamentId == 0)
            {
                return this.BadRequest();
            } else
            {
                return this.RedirectToAction(nameof(SuccessRemove));
            }
            

        }
        

        public IActionResult Info(int id)
        {
            var viewModel = this.tournamentsService.Info<TournamentInfoViewModel>(id);

            return this.View(viewModel);
        }

        public IActionResult Success()
        {
            return this.View();
        }


        public IActionResult SuccessRemove()
        {


            return this.View();
        }

    }
}

Web/TMXN.Web/ViewComponents/TeamViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TMXN.Services.Data;
using TMXN.Web.ViewModels.Teams;
using TMXN.Common;
using TMXN.Web.CustomAttributes;

namespace TMXN.Web.ViewComponents
{
    [ViewComponent(Name = "Team")]
    [ListingViewComponents("Top teamss", "Teams")]
    public class TeamViewComponent : ViewComponent
    {
        private readonly ITeamsService teamsService;

        public TeamViewComponent(ITeamsService teamsService)
        {
            this.teamsService = teamsService;
        }

        public IViewComponentResult Invoke()
        {
            ListingViewComponentsAttribute attr = (ListingViewComponentsAttribute)Attribute.GetCustomAttribute(typeof(TeamViewComponent), typeof(ListingViewComponentsAttribute));
            var viewModel = new ListingTeamsByYearOfCreationViewModel
            {
                Teams =  this.teamsService.GetAll<TeamByYearViewModel>().OrderByDescending(x => x.Points).Take(GlobalConstants.TeamsCountInViewComponent).ToList(),
            };
            viewModel.Header = attr.Header;
            viewModel.Footer = attr.Footer;
            return this.View(viewModel);

        }
    }
}

Web/TMXN.Web/Views/Home/Chat.cshtml
@model TMXN.Web.ViewModels.Chat.ChatViewModel
@{
    this.ViewBag.Title = "ChatRoom";
}


<h1 class="display-4"><span class="badge badge-info">@this.ViewBag.Title</span></h1>

<div id="chat-messages" class="m-2">
    @foreach (var message in Model.Messages)
    {
        <div class="row mt-2 notification">
            <div class="col-9">
                <div class="row">
                    <small class="align-top pl-3 chat-message"><strong>@message.UserName:</strong></small>
                </div>
                <div class="row">
                    <small class="pl-3 align-top">@message.Text</small>
                </div>
            </div>
            <div class="col-3">
                <small class="float-right">@message.CreatedOn</small>
            </div>
        </div>
    }
</div>


<div class="container">
    <div id="message-holder" class="mt-3 d-flex justify-content-start">
        <h4 class="display-4"><span class="badge badge-warning">Message</span></h4>
        <input class="w-75 ml-4 pl-3" type="text" id="messageInput" placeholder="Message..." />
        <button id="sendButton" class="ml-4 btn btn-primary btn-lg">Send</button>

    </div>
    <hr style="height: 5px;" class="bg-info" />
    <div id="messagesList" style="font-size: 28px;">
    </div>
</div>


@section Scripts {

    <script>
        var connection =
            new signalR.HubConnectionBuilder()
                .withUrl("/chatroom")
                .build();

       
       

        connection.on("NewMessage",
            function (message) {
                var chatInfo = `<div>[${message.userName}] ${escapeHtml(message.text)}</div>`;
                $('#messagesList').append(chatInfo);
            });


         $('#sendButton').click(function () {
             var message = $('#messageInput').val();

             connection.invoke("Send", message);


             $('#messageInput').val('');

             location.reload(true);
            
            

         }); 

    
       
        

        connection.start().catch(function (err) {
            return console.error(err.toString());
        });

        function escapeHtml(unsafe) {
            return unsafe
                .replace(/&/g, "&amp;")
                .replace(/</g, "&lt;")
                .replace(/>/g, "&gt;")
                .replace(/"/g, "&quot;")
                .replace(/'/g, "&#039;");
        }
    </script>
   


}

Web/TMXN.Web/Views/Home/HttpError.cshtml
@model int





<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4 text-center">Page Error</h1>
        <p class="lead">
            <div class="text-center">
                <img class="card-img-top" style="width: 16rem;" src="https://drumcreative.com/wp-content/uploads/2018/03/logo-design-mistakes-oops-image.jpg" alt="Card image cap">
            </div>
            <h1 class="display-4 text-center">Not Found Page!</h1>
            <h1 class="display-4 text-center">Error @Model</h1>
      <div class="text-center">
        The things you were looking for were not found, please try again in other pages!
    </div>

    
            <div>
                <a asp-controller="Home" asp-action="Index" type="button" class="btn-lg btn-primary center-block">Go to homepage</a>
            </div>

       
    </div>

Web/TMXN.Web/Views/Home/Index.cshtml
@model TMXN.Web.ViewModels.News.NewsFeedsListViewModel

@using TMXN.Common
@{
    this.ViewData["Title"] = "Home Page";
}

@{ int counter = 0;}

<div class="text-center">

    <h1 class="display-4"><span class="badge badge-info">@GlobalConstants.NewsFeeds</span></h1>

    <div class="card-columns">

        <div class="list-group-horizontal-md d-inline-block" style="width: 220px; background-color: rgba(0,0,255,.1)">

            <vc:tournament></vc:tournament>
            <br>
            <div><a class="nav-link text-dark" asp-area="" asp-controller="Tournaments" asp-action="GetAll">Get involved in!</a></div>
        </div>


        <div class="list-group-horizontal-md d-md-block" style="width: 220px; background-color: rgba(0,0,255,.1)">

            <vc:team></vc:team>
            <br>
            <div><a class="nav-link text-dark" asp-area="" asp-controller="Teams" asp-action="Ranklist">See our ranklist!</a></div>

        </div>

        <div class="list-group-horizontal-md d-md-block" style="width: 220px; background-color: rgba(0,0,255,.1)">

            <vc:award></vc:award>
            <br>
            <div><a class="nav-link text-dark" asp-area="" asp-controller="Teams" asp-action="ShowAll">Get to know our teams!</a></div>

        </div>
    </div>
    <hr style="height: 5px;" class="bg-info" />



</div>
<div class="d-flex justify-content-between">
    <div id="sort-holder" class="form-group w-40 d-flex justify-content-between">

        <label for="sort" class="text-primary font-weight-bold w-30 h4 mt-1 text-right">Order news by</label>
        <form id="order-form" action="/" method="get">

            <select id="sort" class="form-control text-primary pl-2 ml-3 w-30" name="criteria">
                <option value="none" selected>None</option>
                <option value="news-ordered-by-title-ascending">Title</option>
                <option value="news-ordered-by-date-descending">Date (Latest)</option>

            </select>

        </form>
    </div>
</div>

<div class="row">
    @foreach (var news in this.Model.News)
    {
        <div class="card mr-4" style="width: 18rem;">
            <img class="card-img-top" src="@news.ImageUrl" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">@news.Title</h5>

                <a asp-controller="News" asp-action="Info" asp-route-id="@news.Id" class="btn btn-primary center-block">Info</a>

            </div>
        </div>
    }



</div>


@section Scripts
{
   
    <script>

        $('#sort').change(function () {
            $('#order-form').submit();
        });

         
    </script>
  

}